version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
      - poetry-cache:/root/.cache/poetry
      - poetry-venv:/app/.venv
    environment:
      - PYTHONPATH=/app
      - POETRY_VIRTUALENVS_IN_PROJECT=true
      - POETRY_VIRTUALENVS_PATH=/app/.venv
      - PYTHON_VERSION=3.10.12
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - PORT=8000
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 20G
        reservations:
          cpus: '2'
          memory: 6G
    restart: unless-stopped

volumes:
  poetry-cache:
  poetry-venv:
