version: 2.1

orbs:
  python: circleci/python@2.0
  node: circleci/node@5.0
  docker: circleci/docker@2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10-node
    steps:
      - checkout

      # Python setup
      - python/install-packages:
          pkg-manager: poetry
      - node/install-packages:
          pkg-manager: npm

      # Run tests and linting
      - run:
          name: Run Tests
          command: |
            poetry run pytest
            npm test
      - run:
          name: Run Linting
          command: |
            poetry run black --check .
            poetry run flake8
            npm run lint

  deploy:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - setup_remote_docker
      - docker/build:
          image: kod
      - docker/push:
          image: kod

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-test
      - deploy:
          requires:
            - build-and-test
          filters:
            branches:
              only: main
